blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.com/download
    about: Join our Discord server for support and updates.
  - name: Telegram group
    url: https://desktop.telegram.org/
    about: Join our Telegram discussion group for support and updates.
